config/routes.rb
Rails.application.routes.draw do

  get 'mensagem_de_confirmacao' => 'confirm_to_have_donate#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :demand_blood_banks

  match "/admin/update_passwords" => 'admin/update_passwords#edit', via: :get, as: "admin_update_passwords"

  devise_for :user_blood_donators, :skip => [:sessions, :registrations]
  as :user_blood_donator do
    post 'login' => 'sessions#create', :as => :user_blood_donator_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_blood_donator_session

    # get 'cadastroDoador' => 'user_blood_donators/registrations#new' , :as => :new_user_blood_donator_registration
    post 'cadastroDoador' => 'user_blood_donators/registrations#create' , :as => :user_blood_donator_registration

    post 'notificacoes', to: 'user_blood_donators/registrations#active_notification', :as => :user_blood_donator_notification

    get 'madeDonation/:receiveToken', to: 'user_blood_donators/registrations#made_donation', :as => :made_donation

    post 'feedbackDonation' , to: 'user_blood_donators/registrations#feedback_donation' , :as => :feedback_donation
    # =newPrototipo
    # Routes for tests new user_blood_donators/registrations/form_v2

    get 'cancelNotification/:token', to: 'user_blood_donators/registrations#cancel_notification', :as => :cancel_notification


  end

  devise_for :user_blood_banks, :skip => [:sessions, :registrations]
  as :user_blood_bank do
    post 'login' => 'sessions#create', :as => :user_blood_bank_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_blood_bank_session

    get 'cadastroBanco' => 'user_blood_banks/registrations#new', :as => :new_user_blood_bank_registration
    post 'cadastroBanco' => 'user_blood_banks/registrations#create' , :as => :user_blood_bank_registration
  end

  get '/requisitos', to: 'application#requisitos', :as => :dashboard
  get '/necessidadeBanco', to: 'demand_blood_banks#new', :as => :necessidadeBanco

  get 'sign_up_confirmation/:receiveToken', to: 'user_blood_donators/registrations#sign_up_confirmation', :as => :sign_up_confirmation
  # get '/user_blood_donators', to: 'welcome/registrations#sign_up_confirmation', :as => :sign_up_confirmation

  root 'application#index'

  # Routes for components in construction
  get '/components', to: 'components#index'

end

app/models/demand_blood_bank.rb
class DemandBloodBank < ApplicationRecord
    has_and_belongs_to_many :notifications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    @banks = UserBloodBank.where(actived:true)
    send_no_blood_type

  end


  def send_no_blood_type
    @donators = UserBloodDonator.where(blood_type:"", notification:true)
    @donators.each do |donator|
      if(check_donation_interval(donator))
        donator.notification_token = SecureRandom.urlsafe_base64.to_s
        donator.save!
        NotificationMailer.send_email_no_blood_type_donator(donator).deliver_now
        Notification.create! :last_notification => Date.current,
        :appear => false,
        :user_blood_donators_id => donator.id
      end
    end
  end

  def check_donation_interval donator
    notification = Notification.where(user_blood_donators_id:donator.id).last
    if notification.nil?
      return true
    end
    difference = (Date.current - notification.last_notification).to_i
    if difference >= 14
      return true
    end
    return false
  end




end

app/controllers/demand_blood_banks_controller.rb
require 'date'

class DemandBloodBanksController < ApplicationController
  before_action :set_demand_blood_bank, only: [:show, :edit, :update, :destroy]

  # GET /demand_blood_banks/new
  def new
    if current_user_blood_bank
      @demand_blood_bank = DemandBloodBank.new
      @lastUpdateNecessity = DemandBloodBank.last
    else
      return redirect_to root_path
    end
  end

  # GET /demand_blood_banks/1/edit
  def edit
  end

  # POST /demand_blood_banks
  # POST /demand_blood_banks.json
  def create

    @demand_blood_bank = DemandBloodBank.new(demand_blood_bank_params)
    @bank = current_user_blood_bank
    respond_to do |format|
      if @demand_blood_bank.save!

        @donators = UserBloodDonator.where blood_type:(make_demand_array(@demand_blood_bank)), notification:true

        @donators.each do |donator|
          if user_can_recive_email(donator, @demand_blood_bank)
            donator.last_donation_token = SecureRandom.urlsafe_base64.to_s
            donator.notification_token = SecureRandom.urlsafe_base64.to_s
            donator.save!
            response = NotificationMailer.send_email(donator, @bank).deliver_now
            Notification.create! :last_notification => Date.current,
            :appear => false,
            :user_blood_donators_id => donator.id,
            :demand_blood_banks_id => @demand_blood_bank.id
          end
        end
        format.html { }
        format.json { render :show, status: :created, location: @demand_blood_bank }
      else
        format.html { render :new }
        format.json { render json: @demand_blood_bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /demand_blood_banks/1
  # PATCH/PUT /demand_blood_banks/1.json
  def update
    respond_to do |format|
      if @demand_blood_bank.update(demand_blood_bank_params)
        format.html { }
        format.json { render :show, status: :ok, location: @demand_blood_bank }
      else
        format.html { render :edit }
        format.json { render json: @demand_blood_bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demand_blood_banks/1
  # DELETE /demand_blood_banks/1.json
  def destroy
    @demand_blood_bank.destroy
    respond_to do |format|
      format.html { redirect_to demand_blood_banks_url, notice: 'Hospital necessity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_demand_blood_bank
    @demand_blood_bank = DemandBloodBank.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def demand_blood_bank_params
    params.require(:demand_blood_bank).permit(:a_positive, :a_negative, :b_positive, :b_negative, :ab_positive, :ab_negative, :o_positive, :o_negative)
  end

  def user_can_recive_email(user, demand)
    return false unless check_donation_interval user
    return false unless check_last_donation_request user
    true
  end

  def make_demand_array demand
    array = Array.new
    array.push("A+") unless demand.a_positive.nil?
    array.push("A-") unless demand.a_negative.nil?
    array.push("B+") unless demand.b_positive.nil?
    array.push("B-") unless demand.b_negative.nil?
    array.push("AB+") unless demand.ab_positive.nil?
    array.push("AB-") unless demand.ab_negative.nil?
    array.push("O+") unless demand.o_positive.nil?
    array.push("O-") unless demand.o_negative.nil?
    array.push("")
    array
  end

  def check_last_donation_request donator
    last_notification = Notification.where(:user_blood_donators_id => donator.id).last
    if last_notification.nil? || (Date.current - last_notification.last_notification).to_i > 7
      return true
    end
    false
  end

  def check_donation_interval donator
    if donator.last_donation == nil
      return true
    end
    difference_in_days = (Date.current - donator.last_donation).to_i
    if donator.genre.downcase == 'm' && difference_in_days > 60
      return true
    elsif donator.genre.downcase == 'f' && difference_in_days > 90
      return true
    end
    false
  end
end

app/views/application/demand_blood_banks/new.html.erb
<h1 class="u-margin">Solicitar doadores</h1>

<div class="Grid Grid--withGutter">
  <div class="Grid-cell u-desktop-size8of12 u-tablet-sizefull u-mobile-sizefull">

    <%= render 'form', demand_blood_bank: @demand_blood_bank %>
  </div>
  <div class="Grid-cell u-desktop-size4of12 u-tablet-sizefull u-mobile-sizefull">

    <div class="Grid-cell sizefull">
      <div class="Container">
        <div class="Container-header">
          <div class="Grid">
            <div class="Grid-cell u-size4of12">
              <div class="Container-stepBox">
                <span class="Container-step">2</span>
              </div>
            </div>
            <div class="Grid-cell u-size8of12">
              <div class="Container-titleBox">
                <h3 class="Container-title"> Solicitar Doações </h3>
              </div>
            </div>
          </div>
        </div>
        <div class="Container-body">
          <p>Após informar a quantidade de doadores para cada tipo sanguíneo,
            clique aqui para continuar o pedido de solicitação.</p>

            <div class="u-float-center u-margin-bottom-medium">
              <div onclick="Modal.open('.js-modalConfirmRequest')"
              class= "Button Button--medium is-disabled js-nextButton">Avançar</div>
            </div>


          </div>

        </div>
      </div>
    </div>
  </div>


  <div class="u-margin-top-large">
    <span>Última atualização <%= @lastUpdateNecessity %></span>
  </div>
</div>

<!-- MODAL ------------------------------------------>

<div class="Modal js-modalConfirmRequest">

  <div class="Modal-content js-modalContent">
    <div class="Modal-header">
      <div class="Modal-stepBox">
        <div class="Modal-step">
          3
        </div>
      </div>
      <div class="Modal-titleBox">
        <h3 class="Modal-title">
          Confirmar solicitação
        </h3>
      </div>
    </div>

    <div class="Modal-body">
      <div class="u-sizeFull">
        <h2 class="Modal-subsTitle">Doadores Solicitados:</h2>
      </div>

      <div class="Grid">
        <div class="Grid-cell u-desktop-size5of12 u-tablet-size6of12 u-mobile-sizefull">

          <div class="Modal-typesRequest">
            <ul class="js-confirmRequestList">

            </ul>
          </div>
        </div>

        <div class="Grid-cell u-desktop-size7of12 u-tablet-size6of12 u-mobile-sizefull">
          <div class="Modal-confirmation">
            <span>
              Enviar solicitação aos doadores dos tipos sanguíneos necessários?
            </span>
            <div class="Button-group">
              <div class="Button Button--fluid u-size6of12 js-modalButton">
                Cancelar
              </div>
              <div onclick="Modal.open('.js-modalSuccessMessage')" class="Button Button--fluid u-size6of12 is-actived js-modalButton" >
                Confirmar
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



<!-- MODAL ------------------------------------------>

<div class="Modal js-modalSuccessMessage">

  <div class="Modal-content js-modalContent">
    <div class="Modal-header">
      <div class="Modal-stepBox">
        <div class="Modal-step">
          4
        </div>
      </div>
      <div class="Modal-titleBox">
        <h3 class="Modal-title">
          Enviado com sucesso
        </h3>
      </div>
    </div>

    <div class="Modal-body">
      <div class="u-align-center u-padding-left u-padding-right">
        <span class="u-font-size20 ">Seu pedido de solicitação foi recebido com sucesso pela equipe do HemoHeroes.</span>
      </div>
      <div class="u-align-center u-padding-top u-padding-bottom">
        <div onclick="Modal.close('.js-modalSuccessMessage')" class="Button Button--fluid u-size6of12 is-actived ">
          OK
        </div>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Back', demand_blood_banks_path %>