config/routes.rb
Rails.application.routes.draw do

  get 'mensagem_de_confirmacao' => 'confirm_to_have_donate#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :demand_blood_banks

  match "/admin/update_passwords" => 'admin/update_passwords#edit', via: :get, as: "admin_update_passwords"

  devise_for :user_blood_donators, :skip => [:sessions, :registrations]
  as :user_blood_donator do
    post 'login' => 'sessions#create', :as => :user_blood_donator_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_blood_donator_session

    # get 'cadastroDoador' => 'user_blood_donators/registrations#new' , :as => :new_user_blood_donator_registration
    post 'cadastroDoador' => 'user_blood_donators/registrations#create' , :as => :user_blood_donator_registration

    post 'notificacoes', to: 'user_blood_donators/registrations#active_notification', :as => :user_blood_donator_notification

    get 'madeDonation/:receiveToken', to: 'user_blood_donators/registrations#made_donation', :as => :made_donation

    post 'feedbackDonation' , to: 'user_blood_donators/registrations#feedback_donation' , :as => :feedback_donation
    # =newPrototipo
    # Routes for tests new user_blood_donators/registrations/form_v2

    get 'cancelNotification/:token', to: 'user_blood_donators/registrations#cancel_notification', :as => :cancel_notification


  end

  devise_for :user_blood_banks, :skip => [:sessions, :registrations]
  as :user_blood_bank do
    post 'login' => 'sessions#create', :as => :user_blood_bank_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_blood_bank_session

    get 'cadastroBanco' => 'user_blood_banks/registrations#new', :as => :new_user_blood_bank_registration
    post 'cadastroBanco' => 'user_blood_banks/registrations#create' , :as => :user_blood_bank_registration
  end

  get '/requisitos', to: 'application#requisitos', :as => :dashboard
  get '/necessidadeBanco', to: 'demand_blood_banks#new', :as => :necessidadeBanco

  get 'sign_up_confirmation/:receiveToken', to: 'user_blood_donators/registrations#sign_up_confirmation', :as => :sign_up_confirmation
  # get '/user_blood_donators', to: 'welcome/registrations#sign_up_confirmation', :as => :sign_up_confirmation

  root 'application#index'

  # Routes for components in construction
  get '/components', to: 'components#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    @banks = UserBloodBank.where(actived:true)
    send_no_blood_type

  end


  def send_no_blood_type
    @donators = UserBloodDonator.where(blood_type:"", notification:true)
    @donators.each do |donator|
      if(check_donation_interval(donator))
        donator.notification_token = SecureRandom.urlsafe_base64.to_s
        donator.save!
        NotificationMailer.send_email_no_blood_type_donator(donator).deliver_now
        Notification.create! :last_notification => Date.current,
        :appear => false,
        :user_blood_donators_id => donator.id
      end
    end
  end

  def check_donation_interval donator
    notification = Notification.where(user_blood_donators_id:donator.id).last
    if notification.nil?
      return true
    end
    difference = (Date.current - notification.last_notification).to_i
    if difference >= 14
      return true
    end
    return false
  end




end

app/views/application/_about.html.erb
<body>
  <section class="Section Section--small" id="sobre">

    <div class="Section-content">
      <h2 class="u-align-center">
        <a>Sobre</a>
      </h2>
      <div class="Section-text">
        <p>
          O projeto HemoHeroes nasceu de uma ideia de estudantes da área de TI
          submetida no programa Aceleradora Ágil, uma parceria ThoughtWorks, PUCRS
          e Centro de Inovação Microsoft.
        </p>
        <p>
          <div class="logoSobre u-float-right u-margin-top-logo">
            <a href="/"><%= image_tag "logo-sobre" %></a>
          </div>
          Buscamos manter e captar doadores em um sistema único, seguro e acessível
          por todos os bancos de sangue parceiros. Assim nos encarregamos de chamar
          os doadores aptos de acordo com a necessidade dos bancos de sangue, disponibilizar
          informações necessárias para quem quer fazer uma doação, informar a data que o
          doador está apto a doar novamente e divulgar campanhas de doação de
          sangue em sua região.
        </p>
        <p>
          Nosso objetivo é salvar cada vez mais vidas captando novos doadores,
          disponibilizar uma nova ferramenta para os bancos de sangue e criando mais
          conforto aos usuários através de facilidades e transparência.
        </p>
      </div>
    </div>
  </section>
</body>

app/views/application/_hero_image.html.erb
<section class="HeroImage">

  <div class="HeroImage-wrapper">

    <div class="navbar HeroImage-header">

      <div class="HeroImage-headerHamburger js-openNavbar">
      </div>

      <div class="HeroImage-headerContent">


        <div class="HeroImage-headerLogo" >
          <a href="/"><%= image_tag "hemoheroes-logo" %></a>
        </div>

        <div class="HeroImage-headerLinks js-navbarLinks">
          <ul>

            <% if user_blood_donator_signed_in? %>
            <li>
              <%= "Bem-vindo, #{current_user_blood_donator.name}" %>
              <%= link_to('Logout', destroy_user_blood_donator_session_path, :method => :delete) %>

            <% elsif user_blood_bank_signed_in? %>
            <li>
              <%= link_to('Solicitar doadores', new_demand_blood_bank_path) %>
              <%= link_to('Logout', destroy_user_blood_bank_session_path, :method => :delete) %>
            </li>
            <% else %>

            <li><a data-turbolinks="false" data-scroll href="#comoFunciona">Como funciona</a></li>
            <li><a data-turbolinks="false" data-scroll href="#onde">Onde doar</a></li>
            <li><a data-turbolinks="false" data-scroll onclick= "Modal.open('.js-modalRequirements')">Quem pode doar</a></li>
            <li><a data-turbolinks="false" data-scroll href="#sobre">Sobre</a></li>

            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="HeroImage-content">
      <div class="HeroImage-headlineBox">
        <div class="HeroImage-headline">
          Receba notificações de  quando e onde doar sangue
        </div>
        <div class="HeroImage-subHeadline">
          Faça parte dos doadores voluntários do HemoHeroes
        </div>
      </div>

      <div class="HeroImage-benefitsBox">
        <div class="Button Button--large  is-actived-secundary" id="registration_button" onclick="Modal.open('.js-modalRegistration')">
          Quero Me Cadastrar <span class="glyphicon glyphicon-menu-right"></span>
        </div>
        <div class="HeroImage-benefits">
          <ul>
            <li><%= image_tag("/images/green-check.png")%> Localize facilmente onde doar</li>
            <li><%= image_tag("/images/green-check.png")%> Receba notificações por email</li>
            <li><%= image_tag("/images/green-check.png")%> Saiba quando doar novamente</li>
          </ul>
        </div>
      </div>
    </div>

    <div class="HeroImage-footer">
      <div class="HeroImage-friends">
        <div class="fb-like" data-href="https://www.facebook.com/HemoHeroes-1202144513238389/" data-layout="standard" data-action="like" data-show-faces="true" data-share="false"></div>
      </div>



      <div class="HeroImage-learnMore">
        <a data-scroll href="#comoFunciona">
          <div>Saiba mais</div>
          <span class="glyphicon glyphicon-menu-down u-block"></span>
        </a>
      </div>

      <div class="HeroImage-partners">
        Apoio
        <div class="HeroImage-imagesBox">
          <%= image_tag("/images/black-microsoft-innovation-center-logo.png")%>
          <%= image_tag("/images/black-thoughtworks-logo.png")%>
        </div>
      </div>

    </div>

  </div>

</section>

app/views/application/_how_works.html.erb
<section id="comoFunciona" class="Section Section u-align-center">
  <h2 class="u-margin-0">
    <a>Como funciona</a>
  </h2>
  <div class="HowFunction-group">
    <div class="HowFunction">
      <div class="HowFunction-image">
        <%= image_tag "user.png" %>
      </div>
      <div class="HowFunction-name">
        1. Você se <a onclick="Modal.open('.js-modalRegistration')">cadastra</a> no HemoHeroes
      </div>
      <div class="Button Button--smallSecundary is-actived-secundary" onclick="Modal.open('.js-modalRegistration')">
        Cadastre-se aqui <span class="glyphicon glyphicon-menu-right"></span>
      </div>
    </div>
    <div class="HowFunction">
      <div class="HowFunction-image">
        <%= image_tag "hospital.png" %>
      </div>
      <div class="HowFunction-name">
        2. O Banco de Sangue solicita a doação do seu tipo sanguíneo
      </div>
    </div>
    <div class="HowFunction">
      <div class="HowFunction-image">
        <%= image_tag "email.png" %>
      </div>
      <div class="HowFunction-name">
        3. Você recebe por email a solicitação
      </div>
    </div>
    <div class="HowFunction">
      <div class="HowFunction-image">
        <%= image_tag "blood-donator.png" %>
      </div>
      <div class="HowFunction-name">
        4. Atenda a solicitação comparecendo ao Banco de Sangue
      </div>
    </div>
  </div>

  <!-- <div class="Button Button--large  is-actived-secundary" onclick="Modal.open('.js-modalRegistration')">
    Quero Me Cadastrar <span class="glyphicon glyphicon-menu-right"></span>
  </div> -->

</section>

app/views/application/_places_donate.html.erb
<section id="onde" class="Section Section--secondary u-align-center u-margin-top-large">

  <h2 class="u-margin-0">
    <a>Onde doar</a>
  </h2>

  <span class="Section-subtitle">Estes são os hospitais parceiros onde você poderá fazer sua doação</span>

  <div class="Map-group">
    <% @banks.each do |bank| %>
    <div class="Map">
      <div class="Map-name">
        <%= bank.name %>
      </div>

      <!-- =Testes com mapa -->
      <div id="hide" class="js-clickMap<%=bank.id%>" style="display:none;">
        <span class="u-padding-bottom">Quando o <%= bank.name %> precisar, solicitará sua doação por email.</span><br />
        <div class="Button Button--smallSecundary is-actived-secundary u-margin-top-medium u-margin-bottom-small" onclick="Modal.open('.js-modalRegistration')">
          Cadastre-se aqui <span class="glyphicon glyphicon-menu-right"></span>
        </div>
      </div>

      <div class="Map-image" onclick="clickMap.show('.js-clickMap<%=bank.id%>')">
        <%= image_tag("https://maps.googleapis.com/maps/api/staticmap?center=
        #{bank.latitude}, #{bank.longitude}&markers=color:red%7Clabel:H%7C#{bank.latitude},
        #{bank.longitude}&zoom=15&size=400x250&key=AIzaSyBJc6_zyREWQW3SaIg19--mmQFiUUzL94g",
        data:{ nome:bank.name}, alt:"mapa") %>
      </div>

      <div class="Map-address">
        <b>Endereço:</b> <%= bank.address %>
      </div>

      <div class="Map-phone">
        <b>Contato:</b> <%= bank.phone %>
      </div>


    </div>
    <% end %>
  </div>
  <p>Novos bancos de sangue em breve. </p>
</section>

app/views/application/index.html.erb
<%= render 'hero_image' %>
<%= render 'how_works' %>
<%= render 'places_donate' %>
<%= render 'about' %>

<%= render partial: 'application/modals/modal_notification' %>
<%= render partial: 'application/modals/modal_feedback' %>
<%= render partial: 'application/modals/modal_terms' %>
<%= render partial: 'application/modals/modal_map' %>
<%= render partial: 'application/modals/modal_requirements' %>